[prop]
id = "KamModuleX"
name = "Example Module Name"
version = "1.0.0"
versionCode = 1765205540245
author = "Your Name"
description = "Describe your module here"
updateJson = "https://raw.githubusercontent.com/user/repo/branch/update.json"
metamodule = false

[mmrl.repo]
license = "MIT"
license_file = "LICENSE"
homepage = "https://github.com/Your Name/KamModuleX"
readme = "https://github.com/Your Name/KamModuleX/blob/main/README.md"
readme_file = "README.md"
changelog = "https://github.com/Your Name/KamModuleX/blob/main/CHANGELOG.md"
changelog_file = "CHANGELOG.md"
screenshots = []
categories = ["tools"]
keywords = [
    "kam",
    "module",
    "android",
    "template",
]
maintainers = ["Your Name"]
repository = "https://github.com/Your Name/KamModuleX"
documentation = "https://github.com/Your Name/KamModuleX"
issues = "https://github.com/Your Name/KamModuleX/issues"
funding = "https://github.com/sponsors/Your Name"
support = "https://github.com/Your Name/KamModuleX/issues"
donate = ""
cover = ""
icon = "icon.png"
devices = []
arch = ["arm64-v8a"]
require = []
antifeatures = []
max_num = 0
min_api = 21
max_api = 35
verified = false
features = [
    "module-template",
    "customization",
]

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "kam"

[kam.build]
target_dir = "dist"
output_file = "{{id}}-{{versionCode}}"
hooks_dir = "hooks"

[kam.tmpl.variables.repository]
var_type = "string"
required = false
default = "https://github.com/Your Name/KamModuleX"

[kam.workspace]
members = ["."]

[tool]
